# This test job is separated out into its own workflow to be able to obtain a separate badge for it
name: Testing development version of dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test with development versions of dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install --upgrade tox

      - name: Execute notebooks as testing
        id: test_status
        run: tox -e py312-test-devdeps -- --report-log output_log_devdeps.json

      - name: Open issue upon cron failure
        if: |
          failure()
          && steps.test_status.outcome == 'failure'
          && github.event_name == 'pull_request'
          && github.repository_owner == 'nasa-navo'
        uses: scientific-python/issue-from-pytest-log-action@v1
        with:
          log-path: output_log_devdeps.json