# This test job is separated out into its own workflow to be able to obtain a separate badge for it
name: Testing development version of dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test with development versions of dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install --upgrade tox

      - name: Set output for cron
        if: ${{ github.event_name == 'schedule' }}
        env:
          posargs: --report-log cron_output-log.json
        run: echo $posargs

      - name: Execute notebooks as testing
        run: tox -e py312-test-devdeps
